### ISSUE TITLE
Creating a user model for user

### ISSUE THREAD

**Issue by kdpark** [RedstarVentures/optimizesurvey#20]
Creating a user model for user.

distinguish between users and coaches.

**Comment by kdpark** [comment]
Example)

class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)

**Comment by kdpark** [comment]
Giving a permission to coach manually. (managed by one field)

**Comment by kwantopia** [comment]
The way to distinguish is by having a field in

core.EmailUser

the field can be an

```
USER_TYPE_CHOICES = (
    (0, 'client'),
    (1, 'coach'),
    (2, 'expert'),
)

role = models.IntegerField(choices=USER_TYPE_CHOICES, default=0)
```

You can extend USER_TYPE_CHOICES later

On Fri, Aug 9, 2013 at 5:08 PM, kdpark notifications@github.com wrote:

> Example)
> 
> class Article(models.Model):
> author = models.ForeignKey(settings.AUTH_USER_MODEL)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RedstarVentures/optimizesurvey/issues/20#issuecomment-22423318
> .

## 

Kwan Hong Lee, Ph.D.
Technology Director
Redstar Ventures
http://www.redstar.com
617-871-0710
